events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # DNS резолвер для Docker (если используешь переменные)
    resolver 127.0.0.11 valid=30s ipv6=off;

    server {
        listen 80;
        server_name localhost;

        # API запросы
        location /api/ {
            proxy_pass http://backend:8080/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass_header Set-Cookie;
    		proxy_cookie_domain todoapp-backend $host;
    		proxy_cookie_path / /;
        }

        # Swagger UI (если нужно)
        location /swagger {
            proxy_pass http://backend:8080/swagger;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ВСЕ остальные запросы на фронт
        location / {
            proxy_pass http://frontend:4173;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Для WebSocket (если нужно)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}